### ISSUE TITLE
Command Line Input '--help' outputs twice

### ISSUE THREAD

**Issue by NGenetzky** [USGS-EROS/espa-spectral-indices#13]
The message "spectral_indices --help will print the usage statement" and "spectral_indices --help prints the usage information for this application" are both shown and discuss adding the "--help" argument.
Example:
```
>>spectral_indices --help
...(Start of help message)...
spectral_indices --help will print the usage statement

Example: spectral_indices --xml=LT50400331995173AAA02.xml --ndvi --ndmi --nbr --evi --verbose

spectral_indices --version prints the version information for this application
spectral_indices --help prints the usage information for this application
```

**Comment by rdilley-usgs** [comment]
Not sure I follow, find me in the morning

On Wed, Jul 1, 2015 at 3:45 PM, Nathan Genetzky <notifications@github.com>
wrote:

> Example:
>
>  spectral_indices --help
> ...
> spectral_indices --help will print the usage statement
>
>  Example: spectral_indices --xml=LT50400331995173AAA02.xml --ndvi --ndmi
> --nbr --evi --verbose
>
> spectral_indices --version prints the version information for this
> application
> spectral_indices --help prints the usage information for this application
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-spectral-indices/issues/13>.
>



-- 

Ronald D. Dilley Jr.
Innovate!, Inc.

Contractor To:
  USGS Earth Resources Observation and Science Center (EROS)
  47914 252nd Street
  Sioux Falls, SD 57198-9801

Phone: 605.594.2669
Email: rdilley@usgs.gov
Email: rdilley@innovateteam.comhttp://landsat.usgs.gov/CDR_ECV.php

**Comment by gschmidt-usgs** [comment]
Is there an issue here?

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"

**Comment by NGenetzky** [comment]
Maybe it was intentional. My opinion is that the double help message for --help is repetitive. I assumed it was a typo not intentional.

![image](https://cloud.githubusercontent.com/assets/12733783/8477234/2ac97768-208e-11e5-853b-f417d192963d.png)

**Comment by rdilley-usgs** [comment]
Gail, --version and --help examples were added at the bottom of the help,
when a --help example already exists above the "Example:".

On Thu, Jul 2, 2015 at 7:44 AM, Nathan Genetzky <notifications@github.com>
wrote:

> Maybe it was intentional. My opinion is that the double help message for
> --help is repetitive. I assumed it was a typo not intentional.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/12733783/8477234/2ac97768-208e-11e5-853b-f417d192963d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-spectral-indices/issues/13#issuecomment-118020836>
> .
>



-- 

Ronald D. Dilley Jr.
Innovate!, Inc.

Contractor To:
  USGS Earth Resources Observation and Science Center (EROS)
  47914 252nd Street
  Sioux Falls, SD 57198-9801

Phone: 605.594.2669
Email: rdilley@usgs.gov
Email: rdilley@innovateteam.comhttp://landsat.usgs.gov/CDR_ECV.php

**Comment by gschmidt-usgs** [comment]
Issue fixed and pushed to the central repo on dev_v2.2.0 branch.
