### ISSUE TITLE
Enhanced Vegetation Index (EVI) implemented correctly

### ISSUE THREAD

**Issue by sfoga-usgs** [USGS-EROS/espa-spectral-indices#17]
The EVI equation is missing the gain factor (2.5). I checked back to MODIS sources (collection 5: http://vip.arizona.edu/documents/MODIS/MODIS_VI_UsersGuide_01_2012.pdf and collection 6: http://vip.arizona.edu/documents/MODIS/MODIS_VI_UsersGuide_June_2015_C6.pdf) and they have always implemented their equation with a gain factor applied.

Academic source for the equation: http://research.eeescience.utoledo.edu/lees/papers_pdf/Huete_2002_RemSensEnv.pdf

Where we have EVI implemented: https://github.com/USGS-EROS/espa-spectral-indices/blob/master/src/make_spectral_index.c#L304 - it should be: 

ratio = 2.5 * (the equation currently implemented)

**Comment by gschmidt-usgs** [comment]
Updated EVI to apply the gain factor.  This is implemented in the evi_hot_release branch and will be in version 2.3.0.
