### ISSUE TITLE
VI Global Attribute Shortname

### ISSUE THREAD

**Issue by rdilley-usgs** [USGS-EROS/espa-spectral-indices#6]
```
Since we started packaging all the VI's into a single HDF, we no longer have individual
shortnames in the global attributes.  Instead of being L7ENDVI for example (Landsat
ETM+ NDVI), it now says L7EVI.  Meaning of course Landsat 7 VI, but looking like Landsat
7 EVI.  Suggest updating that sometime.  L4TVI and L5TVI are okay.

```

Original issue reported on code.google.com by `kalliente` on 2013-12-03 19:13:30

**Comment by gschmidt-usgs** [comment]
This was fixed in a previous release.

        <band product="spectral_indices" source="sr_refl" name="sr_ndvi" category="index" data_type="INT16" nlines="7791" nsamps="7671" fill_value="-9999" saturate_value="20000" scale_factor="0.000100">
            <short_name>LC8SR_NDVI</short_name>
            <long_name>normalized difference vegetation index</long_name>
            <file_name>LC80410272013181LGN00_sr_ndvi.img</file_name>
            <pixel_size x="30" y="30" units="meters"/>
            <resample_method>none</resample_method>
            <data_units>band ratio index value</data_units>
            <valid_range min="-10000" max="10000"/>
            <app_version>spectral_indices_2.2.0</app_version>
            <production_date>2015-09-29T19:44:43Z</production_date>
        </band>
        <band product="spectral_indices" source="sr_refl" name="sr_ndmi" category="index" data_type="INT16" nlines="7791" nsamps="7671" fill_value="-9999" saturate_value="20000" scale_factor="0.000100">
            <short_name>LC8SR_NDMI</short_name>
            <long_name>normalized difference moisture index</long_name>
            <file_name>LC80410272013181LGN00_sr_ndmi.img</file_name>
            <pixel_size x="30" y="30" units="meters"/>
            <resample_method>none</resample_method>
            <data_units>band ratio index value</data_units>
            <valid_range min="-10000" max="10000"/>
            <app_version>spectral_indices_2.2.0</app_version>
            <production_date>2015-09-29T19:44:43Z</production_date>
        </band>
        <band product="spectral_indices" source="sr_refl" name="sr_nbr" category="index" data_type="INT16" nlines="7791" nsamps="7671" fill_value="-9999" saturate_value="20000" scale_factor="0.000100">
            <short_name>LC8SR_NBR</short_name>
            <long_name>normalized burn ratio</long_name>
            <file_name>LC80410272013181LGN00_sr_nbr.img</file_name>
            <pixel_size x="30" y="30" units="meters"/>
            <resample_method>none</resample_method>
            <data_units>band ratio index value</data_units>
            <valid_range min="-10000" max="10000"/>
            <app_version>spectral_indices_2.2.0</app_version>
            <production_date>2015-09-29T19:44:43Z</production_date>
        </band>
